In [2]:
import numpy as np
import scipy.linalg as lin

In [3]:
A = np.array([[1,2,3],[4,5,6]]) #matrices are defined as nump arrays

print('The matrix A=')
print(A)
print('\n')

The matrix A=
[[1 2 3]
 [4 5 6]]




In [4]:
# for accessing individual entries of A use standard python indexing
a13 = A[0][2]
# or
a13 = A[0,2]

print(f"The component a13 of A = {a13}\n")

The component a13 of A = 3



In [5]:
# finding the transpose of A
B = A.T
# or
B = np.transpose(A)

print('The transpose of A =')
print(B) 

The transpose of A =
[[1 4]
 [2 5]
 [3 6]]


In [6]:
# to calculate the sum of matrices, the dimensions must be the same

C = np.add(A,2*A)
# or
C = A + 2*A

print('The sum of A and 2A is =')
print(C)

The sum of A and 2A is =
[[ 3  6  9]
 [12 15 18]]


In [7]:
# multiply two matrices (dimensions must allow for the operation)

C = np.matmul(A,B)
# or
C =np.dot(A,B) # this is not preferred
# or
C = A @ B

# it is important to remember that AB does not always equal BA
# when it comes to matrix multiplication

print("Are the dimensions for matrix multiplication correct?")
print(np.shape(A)[1]==np.shape(B)[0]) # checking if number of columns in A
print()                                # equals number of rows in B

print("The product of A and B =")
print(C)
print()

Are the dimensions for matrix multiplication correct?
True

The product of A and B =
[[14 32]
 [32 77]]



In [13]:
A = np.array([[-7,-5,3],[-1,-8,2],[4,-1,0]])

# find the determinant of A (A needs to be square)
A_det = lin.det(A)


# finding the inverse of A (A needs to be square)
A_inv = lin.inv(A)


print('New A =')
print(A)
print()
print(f"The determinant of A = {A_det}")
print()
print('The inverse of A = ')
print(A_inv)
print()
print('The product of A and its inverse is the identity')
print(A_inv@A)

# we can see here that using python to calculate the inverse generates
# a matrix that intoduces a small amount of error since when A is multiplied
# with its inverse we are getting very small values where there should be 0s

New A =
[[-7 -5  3]
 [-1 -8  2]
 [ 4 -1  0]]

The determinant of A = 45.0

The inverse of A = 
[[ 0.04444444 -0.06666667  0.31111111]
 [ 0.17777778 -0.26666667  0.24444444]
 [ 0.73333333 -0.6         1.13333333]]

The product of A and its inverse is the identity
[[ 1.00000000e+00 -5.55111512e-17  2.77555756e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 8.88178420e-16  2.22044605e-16  1.00000000e+00]]


In [9]:
# the idenetity matrix
I = np.identity(4)

# the zero matrix
Z_mat = np.zeros((3,3))

print('The 4x4 identity matrix')
print('I')
print('and the 3x3 zero matrix')
print(Z_mat)
print()

The 4x4 identity matrix
I
and the 3x3 zero matrix
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [10]:
# in order to retrieve a particular unit vecotr or coordinate vector
# use python array slicing in order to extract a particular column from the
# appropriate identity matrix

e3 = np.identity(4)[:,[2]]

print('The third unit vector is')
print(e3)
print()

The third unit vector is
[[0.]
 [0.]
 [1.]
 [0.]]



In [11]:
# we will use a built in function to solve a linear system and then later
# work to understand how python actually computes the solution

# solve A x = b

A = np.array([[-7,-5],[-1,-8]])
b = np.array([[1],[3]])

xx = lin.solve(A,b)

print('Solving A x = b ...')
print('x =')
print(xx)
print()


# demonstrating the accuracy of the computed solution
print(b)
print(A @ xx)

Solving A x = b ...
x =
[[ 0.1372549 ]
 [-0.39215686]]

[[1]
 [3]]
[[1.]
 [3.]]


In [12]:
# LU decomposition without pivoting

def LU_NoPivot(A):
    
    n = np.shape(A)[0] # extracting number of rows of A
    U = np.copy(A)
    L = np.identity(n)

    for jj in range(n-1):
        for ii in range(jj+1,n):
            L[ii,jj] = U[ii,jj]/U[jj,jj]
            U[ii,:] = U[ii,:]-L[ii,jj] * U[jj,:]

    return L,U

A = np.array([[2,1,1,0],[4,3,3,1],[8,7,9,5],[6,7,9,8]])

L,U = LU_NoPivot(A)
print(L,'\n',U,'\n')
print(np.matmul(L,U)-A)



[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [4. 3. 1. 0.]
 [3. 4. 1. 1.]] 
 [[2 1 1 0]
 [0 1 1 1]
 [0 0 2 2]
 [0 0 0 2]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
